//! Defines the `EngramVariant` enum for distinguishing between light and dark themes.
//!
//! This module provides custom (de)serialization to be lenient with user input
//! in `palette.toml` files, and bridges the gap between Kenaz's internal variant
//! type and Zed's auto-generated `AppearanceContent` schema type.

use crate::schema::AppearanceContent;
use serde::{Deserialize, Serialize};
use strum::EnumString;

/// Represents whether the theme is light or dark.
///
/// This is used to match user palettes with the correct engram database entries
/// and to generate the appropriate Zed `AppearanceContent`.
#[derive(Debug, Clone, Copy, EnumString, Serialize)]
pub enum EngramVariant {
    Dark,
    Light,
}

/// Allows toggling the variant using the unary `!` operator.
///
/// This is syntactic sugar for cross-mode style transfers, allowing you to write
/// `!EngramVariant::Dark` to get `EngramVariant::Light`.
impl std::ops::Not for EngramVariant {
    type Output = Self;
    fn not(self) -> Self::Output {
        match self {
            Self::Dark => Self::Light,
            Self::Light => Self::Dark,
        }
    }
}

/// Custom case-insensitive deserializer
///
/// Allows the TOML/JSON parser to accept "dark", "Dark", or "DARK" seamlessly,
/// preventing the build failures due to simple casing errors in the config file.
impl<'de> Deserialize<'de> for EngramVariant {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let s = String::deserialize(deserializer)?;
        match s.to_lowercase().as_str() {
            "dark" => Ok(EngramVariant::Dark),
            "light" => Ok(EngramVariant::Light),
            _ => Err(serde::de::Error::custom(format!(
                "unknown variant `{s}`, expected `dark` or `light`",
            ))),
        }
    }
}

/// Converts a Zed `AppearanceContent` (generated by typify) into an `EngramVariant`.
impl From<AppearanceContent> for EngramVariant {
    fn from(value: AppearanceContent) -> Self {
        match value {
            AppearanceContent::Dark => Self::Dark,
            AppearanceContent::Light => Self::Light,
        }
    }
}

/// Converts an `EngramVariant` back into a Zed `AppearanceContent` for final theme generation.
impl From<EngramVariant> for AppearanceContent {
    fn from(value: EngramVariant) -> Self {
        match value {
            EngramVariant::Dark => AppearanceContent::Dark,
            EngramVariant::Light => AppearanceContent::Light,
        }
    }
}
