//! Provides the `ColorMutable` derive macro for the Kenaz theme engine
//!
//! This macro automatically generates the implementation of the
//! `ColorMutable` trait for any struct or enum generated by `typify`
//! It recursively traverses the data structure at runtime, building flat
//! dotted paths (e.g., `editor.background`) to query the engram database.

use proc_macro::TokenStream;
use quote::quote;
use syn::{Data, DeriveInput, Fields, parse_macro_input};

/// Derives the `ColorMutable` trait for a given struct or enum
///
/// This allows the Kenaz engine to recursively apply color vectors (from engrams)
/// to every color field within the type hierarchy
#[proc_macro_derive(ColorMutable)]
pub fn derive_color_mutable(input: TokenStream) -> TokenStream {
    let input = parse_macro_input!(input as DeriveInput);
    let name = &input.ident;

    // Generates the body of the `apply_colors` method based on the data type.
    let body = match &input.data {
        Data::Struct(data) => match &data.fields {
            Fields::Named(fields) => {
                let calls = fields.named.iter().map(|f| {
                    let field_name = f.ident.as_ref().unwrap();
                    let field_name_str = field_name.to_string();

                    quote! {
                        {
                            current_path.with_segment(#field_name_str, |path| {
                                self.#field_name.apply_colors(path, engram, anchors);
                            });
                        }
                    }
                });
                quote! {#(#calls)* }
            }
            Fields::Unnamed(fields) => {
                let calls = fields.unnamed.iter().enumerate().map(|(i, _)| {
                    let index = syn::Index::from(i);
                    quote! {
                        {
                            current_path.with_index(#i, |path| {
                                self.#index.apply_colors(path, engram, anchors);
                            });
                        }
                    }
                });
                quote! { #(#calls)* }
            }
            Fields::Unit => quote! {},
        },
        Data::Enum(data) => {
            let arms = data.variants.iter().map(|v| {
                let ident = &v.ident;
                let ident_str = ident.to_string();
                match &v.fields {
                    Fields::Named(fields) => {
                        let field_idents = fields.named.iter().map(|f| f.ident.as_ref().unwrap());
                        let field_idents2 = field_idents.clone();
                        let field_strs = fields
                            .named
                            .iter()
                            .map(|f| f.ident.as_ref().unwrap().to_string());
                        quote! {
                            #name::#ident { #(#field_idents),* } => {
                                #(
                                    current_path.with_segment(#ident_str, |path| {
                                        path.with_segment(#field_strs, |inner| {
                                            #field_idents2.apply_colors(inner, engram, anchors);
                                        });
                                    });
                                )*
                            }
                        }
                    }
                    Fields::Unnamed(fields) => {
                        // Generate unique identifiers for tuple variants (e.g., _val0, _val1)
                        let bindings = (0..fields.unnamed.len()).map(|i| {
                            proc_macro2::Ident::new(
                                &format!("_val{}", i),
                                proc_macro2::Span::call_site(),
                            )
                        });
                        let bindings2 = bindings.clone();
                        let indices = 0..fields.unnamed.len();
                        quote! {
                            #name::#ident( #(#bindings),* ) => {
                                #(
                                    current_path.with_segment(#ident_str, |path| {
                                        path.with_index(#indices, |inner| {
                                            #bindings2.apply_colors(inner, engram, anchors);
                                        });
                                    });
                                )*
                            }
                        }
                    }
                    Fields::Unit => quote! { #name::#ident => {} },
                }
            });
            quote! {
                match self {
                    #(#arms)*
                }
            }
        }
        Data::Union(_) => quote! {},
    };

    // Inject the generated body into the trait implementation
    let expanded = quote! {
        impl crate::visitor::ColorMutable for #name {
            fn apply_colors(&mut self, current_path: &mut String, engram: &crate::engram::Engram, anchors: &crate::palette::Colors) {
                use crate::visitor::PathBuffer;
                #body
            }
        }
    };

    expanded.into()
}
