//! Build script for `kenaz_core`
//!
//! This script runs before the main compilation. It downloads the official
//! Zed theme JSON schema, generates strongly-typed Rust structs using `typify`,
//! and injects the `ColorMutable` derive macro into every generated type.
//! The final code is written to `OUT_DIR/schema.rs` to be included in the crate.

use std::{env, fs, path::Path};
use syn::{parse2, visit_mut::VisitMut};
use typify::{TypeSpace, TypeSpaceSettings};

/// A syntax tree visitor that injects the `ColorMutable` derive macro
/// into all generated structs and enums
struct DeriveInjector;

impl VisitMut for DeriveInjector {
    fn visit_item_struct_mut(&mut self, i: &mut syn::ItemStruct) {
        i.attrs
            .push(syn::parse_quote! { #[derive(kenaz_macros::ColorMutable)] });
    }

    fn visit_item_enum_mut(&mut self, i: &mut syn::ItemEnum) {
        i.attrs
            .push(syn::parse_quote! { #[derive(kenaz_macros::ColorMutable)] });
    }
}

fn main() {
    let local_path = Path::new("schema.json");

    // 1. Download schema only if it does not exists in local path
    if !local_path.exists() {
        println!("cargo:warning=Downloading Zed schema...");
        let schema_url = "https://zed.dev/schema/themes/v0.2.0.json";
        if let Ok(mut resp) = ureq::get(schema_url).call() {
            if resp.status().is_success() {
                let text = resp.body_mut().read_to_string().unwrap_or_default();
                let _ = std::fs::write(local_path, &text);
            }
        }
    }

    // 2. Tell Cargo to rebuild script only if schema file or build.rs changes
    println!("cargo:rerun-if-changed=schema.json");
    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:warning=Build.rs is running...");

    let schema_content = fs::read_to_string(local_path)
        .expect("Failed to read schema.json. Please check your internet connection.");
    let schema = serde_json::from_str::<schemars::schema::RootSchema>(&schema_content).unwrap();

    // Generate Rust code from the JSON schema using typify
    let mut type_space = TypeSpace::new(TypeSpaceSettings::default().with_struct_builder(true));
    type_space.add_root_schema(schema).unwrap();

    // Parse the generated code into a Syntax Tree (AST) for modification
    let mut file: syn::File =
        parse2(type_space.to_stream()).expect("Successfully parsed generated code");

    // Visit the AST and inject our custom derive macro into every struct and enum
    let mut injector = DeriveInjector;
    syn::visit_mut::visit_file_mut(&mut injector, &mut file);

    // Format the final code nicely before writing it to disk
    // (allows the dev to browse the file without wanting to gouge his/her eyes :))
    let final_code = format!(
        "// Auto-generated by typify and build.rs\n{}",
        prettyplease::unparse(&file)
    );

    // Write the final file to the OUT_DIR so the compiler can include it
    let out_dir = env::var("OUT_DIR").unwrap();
    let dest_path = Path::new(&out_dir).join("schema.rs");
    fs::write(&dest_path, final_code).unwrap();
}
