[package]
name = "kenaz_core"
version = "1.1.0"
edition = "2024"
build = "build.rs"
homepage = "https://github.com/reeves-48777/kenaz"

[dependencies]
kenaz_macros = { path = "../kenaz_macros" }
serde.workspace = true
serde_json.workspace = true
rusqlite.workspace = true
palette.workspace = true
typify.workspace = true
dirs = "6.0.0"
dotenvy = { version = "0.15.7", optional = true }
rayon = "1.12.0"
strum = { version = "0.28.0", features = ["derive"] }
tracing.workspace = true
tar.workspace = true
flate2.workspace = true
ureq = { workspace = true, optional = true }
thiserror = "2.0.20"

[dev-dependencies]
criterion = { version = "0.8.2", features = ["html_reports"] }

[build-dependencies]
typify.workspace = true
ureq.workspace = true
syn = { workspace = true, features = ["full", "parsing", "visit-mut"]}
quote.workspace = true
proc-macro2.workspace = true
serde_json.workspace = true
schemars = "0.8"
prettyplease = "0.3.0"
kenaz_macros = { path = "../kenaz_macros"}


[features]
dev-tools = ["dep:dotenvy", "dep:ureq"]

[[bench]]
name = "kenaz_bench"
harness = false
path = "benches/bench.rs"
